
TILEWIDTH = 16
TILEHEIGHT = 16
NROWS = 36
NCOLS = 28
SCREENWIDTH = NCOLS*TILEWIDTH
SCREENHEIGHT = NROWS*TILEHEIGHT
SCREENSIZE = (SCREENWIDTH, SCREENHEIGHT)

BLACK = (0, 0, 0)
YELLOW = (255, 255, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)

STOP = 0
UP = 1
DOWN = -1
LEFT = 2
RIGHT = -2

PACMAN = 0
GHOST = 3

PELLET = 1
POWERPELLET = 2

SEEK = 1
FLEE = 2
WANDER = 3
GO_CRAZY = 4

#TESTS
SEEKtoWANDER = 1
WANDERtoSEEK = 2
WANDERtoFLEE = 3
FLEEtoSEEK = 4

KILL_GHOST = "Kill Ghost"
EAT_SUPERPELLETS = "Eat SuperPellets"
FOLLOW_PATH_TO_TARGET = "Follow Path To Target"
GO_IN_SAME_QUADRANT = "Go in same quadrant"
ACCELERATE = "Accelerate"
VISIT_ANOTHER_QUADRANT = "Visit another quadrant"
WANDER = "Wander"
GO_CLOSEST_CORNER = "Go to closest corner"

TOP_LEFT = 1
TOP_RIGHT = 2
BOT_LEFT = -2
BOT_RIGHT = -1